config/routes.rb
Rails.application.routes.draw do
  resources :my_account, only: [:index, :update]
  resources :tags, only: [:index, :create, :new]
  resources :answers
  resources :questions do
    collection do
      get :questions_by_me
    end
  end
  root 'home#index'

  devise_for :users

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :tags

  belongs_to :user
  has_many :answers
  has_many :question_tags

  after_create :create_question_tags
  after_update :create_question_tags

  def create_question_tags
    if !tags.nil?
      question_tags.destroy_all
      tags.each {|tag| self.question_tags.create(tag_id: tag)}
    end  
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  def questions_by_me
    @questions = current_user.questions
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = @question.answers
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.create(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :tags => [])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => "form-horizontal question" } do |f| %>

<% if @question.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@question.errors.count, "error") %>
      prohibited this question from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="form-group">
  <%= f.label :title, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <%=f.error_span(:title) %>
</div>
<div class="form-group">
  <%= f.label :description, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_area :description, :class => 'form-control' %>
  </div>
  <%=f.error_span(:description) %>
</div>
<div class="form-group">
  <%= f.label :tags, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.select(:tags, options_for_select(Tag.all.map {|s| [s.name, s.id]},@question.question_tags.pluck(:tag_id)),{ :include_blank => "Please select"}, { :multiple => true, :size => 5 }) %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn btn-default' %>
  </div>
</div>

<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= link_to question.title, question_path(question) %></td>
        <td><%= question.description %></td>
        <td><%= question.user.email %></td>
        <td><%= time_ago_in_words(question.created_at) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Ask Question', new_question_path, :class => 'btn btn-primary' %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/questions_by_me.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1>Questions asked by you..</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= link_to question.title, question_path(question) %></td>
        <td><%= question.description %></td>
        <td><%= question.user_id %></td>
        <td><%=l question.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Ask Question', new_question_path, :class => 'btn btn-primary' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%= @question.title %></h1>
</div>

<dl class="dl-horizontal">

  <dt>
    <strong><%= model_class.human_attribute_name(:description) %>:</strong>
  </dt>
  <dd><%= @question.description %></dd>
  <dt>
    <strong>Asked by user:</strong>
  </dt>
  <dd><%= @question.user_id %></dd>
  <dt>
    <strong>Tagged in:</strong>
  </dt>
  <dd>
    <% @question.question_tags.each do |q| %>
    <kbd><%= q.tag.try(:name) %></kbd>
    <% end %>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              questions_path, :class => 'btn btn-default'  %>
<% if current_user == @question.user %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(@question), :class => 'btn btn-default' %>
<% end %>
<% if current_user && current_user != @question.user %>
<%= form_for Answer.new,:url => url_for(:controller => 'answers', :action => 'create'), :html => { :class => "form-horizontal answer" } do |f| %>
<div class="form-group">
  <label for="pwd">Share Your Resposne</label>
  <%= f.text_area :description, :class => 'form-control', :placeholder => 'Type here...' %>
  <%= f.hidden_field :question_id, value: @question.id %>
</div>
<button type="submit" class="btn btn-success">Submit</button>
<% end %>
<% end %>
<% if !current_user %>
<p>
  <em><%= link_to 'Login', new_user_session_path %>
    to share your response.</em>
</p>
<% end %>

<h2>User Responses:</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>User Id</th>
      <th>Answer</th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |ans| %>
    <tr>
      <td><%= ans.user_id %></td>
      <td>
        <em><%= ans.description %></em>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>