config/routes.rb
Rails.application.routes.draw do
  resources :my_account, only: [:index, :update]
  resources :tags, only: [:index, :create, :new]
  resources :answers
  resources :questions do
    collection do
      get :questions_by_me
    end
  end
  root 'home#index'

  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @questions = current_user.might_be_interseted_questions
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%- model_class = Question -%>
<div class="container">
  <div class="jumbotron">
    <h1>Welcome</h1>
    <p>Our Forum mission is to share and grow the world’s knowledge.</p>
    <p><strong><%= link_to 'Browse through all questions', questions_path %></strong></p>
  </div>
</div>
<% if current_user %>
<h2><em>Questions that you may wish to answer</em></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= link_to question.title, question_path(question) %></td>
        <td><%= question.description %></td>
        <td><%= question.user.email %></td>
        <td><%= time_ago_in_words(question.created_at) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Update your interests to get relevant suggestions', my_account_index_path, :class => "btn btn-success" %>
<% end %>